package installator.stages.config;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author cfif11
 */
class LicensePanel extends StagePanel<Boolean> {
    private JPanel panel1;
    private JCheckBox checkBox1;
    private JTextPane textPane1;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JLabel label1;
    private JLabel label2;

    LicensePanel(int index, String text, String question) {
        super(index);
        init();
        label2.setText(question);
        textPane1.setText(text);
        button3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
				calcData();
            }
        });
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }


    @Override
    public JPanel getGUI() {
        return panel1;
    }

    @Override
    protected void init() {
        panel1.setSize(400, 300);
        label1.setText("Лицензионное соглашение");
        button1.setText("Назад");
        button2.setText("Вперед");
        button3.setText("Отмена");
        textPane1.setText("Принять");
    }

    @Override
    protected void calcData() {
		data = checkBox1.isSelected();
		super.calcData();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.SOUTH);
        label2 = new JLabel();
        label2.setText("Label");
        panel2.add(label2, BorderLayout.CENTER);
        checkBox1 = new JCheckBox();
        checkBox1.setText("CheckBox");
        panel2.add(checkBox1, BorderLayout.EAST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.SOUTH);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel3.add(panel4, BorderLayout.EAST);
        button1 = new JButton();
        button1.setText("Button");
        panel4.add(button1);
        button2 = new JButton();
        button2.setText("Button");
        panel4.add(button2);
        button3 = new JButton();
        button3.setText("Button");
        panel4.add(button3);
        textPane1 = new JTextPane();
        panel1.add(textPane1, BorderLayout.CENTER);
        label1 = new JLabel();
        label1.setEnabled(false);
        label1.setText("Label");
        panel1.add(label1, BorderLayout.NORTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
