package installer.stages.config;

import javax.swing.*;
import java.awt.*;

/**
 * @author cfif11
 */
public class BooleanPanel extends StagePanel<Boolean> {
	private JPanel panel1;
	private JButton button2;
	private JButton button3;
	private JCheckBox checkBox1;
	private JLabel label;

	public BooleanPanel(int index, String question, String answer) {
		super(index);
		init();
		label.setText(question);
		checkBox1.setText(answer);
		button3.addActionListener(exitListener);
		button2.addActionListener(nextListener);
	}

	@Override
	public JPanel getGUI() {
		return panel1;
	}

	@Override
	protected void init() {
		panel1.setSize(400, 300);
		button2.setText("Вперед");
		button3.setText("Отмена");
	}

	@Override
	protected void calcData() {
		data = checkBox1.isSelected();
		super.calcData();
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new BorderLayout(0, 0));
		panel1.add(panel2, BorderLayout.SOUTH);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		panel2.add(panel3, BorderLayout.EAST);
		button2 = new JButton();
		button2.setText("Button");
		panel3.add(button2);
		button3 = new JButton();
		button3.setText("Button");
		panel3.add(button3);
		label = new JLabel();
		label.setText("Label");
		panel1.add(label, BorderLayout.CENTER);
		checkBox1 = new JCheckBox();
		checkBox1.setText("CheckBox");
		panel1.add(checkBox1, BorderLayout.EAST);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
