package installer.stages.config;

import javax.swing.*;
import java.awt.*;

/**
 * @author cfif11
 */
public class StartPanel extends StagePanel<Boolean> {
	private JPanel panel1;
	private JButton button1;
	private JButton button2;
	private JTextPane textPane1;

	public StartPanel(int index, String text) {
		super(index);
		init();
		textPane1.setText(text + " Для продолжения нажмите кнопку \"Продолжить\"");
		button1.addActionListener(exitListener);
		button2.addActionListener(nextListener);
	}

	@Override
	public JPanel getGUI() {
		return panel1;
	}

	@Override
	protected void init() {
		panel1.setSize(400, 300);
		button2.setText("Продолжить");
		button1.setText("Выход");
	}

	@Override
	protected void calcData() {
		data = true;
		super.calcData();
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new BorderLayout(0, 0));
		panel1.add(panel2, BorderLayout.SOUTH);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		panel2.add(panel3, BorderLayout.EAST);
		button1 = new JButton();
		button1.setText("Button");
		panel3.add(button1);
		button2 = new JButton();
		button2.setText("Button");
		panel3.add(button2);
		textPane1 = new JTextPane();
		panel1.add(textPane1, BorderLayout.CENTER);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
